### ISSUE TITLE
TagLib: ID3v2.4 no longer supports the frame type TDAT.  It will be discarded from the tag.

### ISSUE THREAD

**Issue by CryVeck** [LouisH-760/MusicPlayer#11]
Cannot read cover from few musics. (Deezer musics)

**Comment by LouisH-760** [comment]
This seems to be an issue on VLCJ or LibVLC's end. I don't think this is an issue with the album cover, but with the tagging of the mp3 files in themselves. I have nearly no mp3 files, so i can't test this sadly.

**Comment by CryVeck** [comment]
Update vlc solve the issue
