### ISSUE TITLE
Previous action freeze

### ISSUE THREAD

**Issue by CryVeck** [LouisH-760/MusicPlayer#15]
No crash log. Just freeze button push frame and cut music.
Context (reproductible):
-Run player, with music (to be faster set music near the end).
-Minimize or unfocus the player
-Wait player change music
-Go back on the player
-Now if you try to go back on the preceden music (with previous button, or shortcut) it will freeze the player and stop playing music.

**Comment by LouisH-760** [comment]
I also get that on my end

**Comment by LouisH-760** [comment]
is it only when skipping to the previous song or does this happen with any action?

**Comment by CryVeck** [comment]
only with previous song.
In particular :
- if the player play music A and go to B without focus
- You can go B next to C etc...
- You can go C previous to B
- But B previous to A will cause freeze

**Comment by CryVeck** [comment]
Rectification :
After reading a music and auto go to next, go previous will freeze on "players.get(position).play();" operation.

**Comment by CryVeck** [comment]
Seems to be method of control in "mediaPlayerComponent.mediaPlayer().controls()" that causes freeze

**Comment by CryVeck** [comment]
The freez is due to the Runnable "finishedAction", when ask to do previous() on end, return the end song will cause freeze again.

**Comment by CryVeck** [comment]
**Needed code structuration changes to solve that issue.**
