### ISSUE TITLE
Player redesign

### ISSUE THREAD

**Issue by CryVeck** [LouisH-760/MusicPlayer#19]
Player seems to need to be optimize and avoid all these track loading (maybe a buffer with length of 2)

**Comment by LouisH-760** [comment]
There is a branch that tried to do this, but in it's current state it is highly unstable. With a rewrite, it can probably be made stable. For that, the playing track has to be stopped BEFORE the new track starts playing, in contrary to what is done now. I can do these changes on the branch and notify you. However, i don't think it will bring much.

**Comment by CryVeck** [comment]
Done in the vlcj-buffered-player branch
