### ISSUE TITLE
GUI Doesn't update when it is on a different workspace

### ISSUE THREAD

**Issue by LouisH-760** [LouisH-760/MusicPlayer#5]
On linux mint, if the song changes while the player is not in the current workspace, the title label won't update. Furthermore, even if the song didn't change, on the next change the label won't update.

**Comment by CryVeck** [comment]
Did the cover image update ?

**Comment by LouisH-760** [comment]
This is probably due do some extent of the rendering being disabled while away, as the label is only ever updated upon a track change. If this is the problem, it can be solved in two ways:
- update the label every time the playback position changes.
    - pros: already built-in, very simple change
    - cons: calling a method that needs to be called only once per song at least thousands of times
- have the window have a listener to know when it regains focus, and update the label at this point too
    - pros: only done when necessary
    - cons: requires more modifications to implement

I personally would go with the second method, which would be (to me) a proper fix and not a hack like the first one, and sacrifices less performance.
